<?php 
if($_COOKIE['user'])
		{
			setcookie("user");
			setcookie("id");
			setcookie("admin");
			unset($_COOKIE['user']);
			unset($_COOKIE['id']);
			unset($_COOKIE['admin']);
			header("location:index.html");
		}
	else
		{
			header("location:index.html");
		}
?>